### ISSUE TITLE
How to do parallel data states?

### ISSUE THREAD

**Issue by josiahmoreno** [KStateMachine/kstatemachine#100]
I have a DataState that is called StateA with ChildMode.PARALLEL, how do I make sure its child datastates get the original data? I keep getting `Last data is not available yet in`

**Comment by nsk90** [comment]
Hi, `DataState` can receive its data by two ways:
1) By DataEvent targeting this state
2) By default data value set  on state creation point

Data is NOT propagated over DataState hierarchy in some way.

**Comment by nsk90** [comment]
closing as stale
