### ISSUE TITLE
Expose sourceState to the transition block.

### ISSUE THREAD

**Issue by Zeliret** [KStateMachine/kstatemachine#106]
Hi there, first of all thank you for the library! 

I'm currently playing with it and discovered a small limitation.
Imagine that you have many states which can or cannot be cancellable. 
I can define a transition either for each of them separately or I can try to group them in some way so they can inherit transitions.
But what if I need a more dynamic way, where each state exposes to the UI layer a `cancellable` variable and inside the state machine definition I can just write a single parent transition like this:
```kotlin
transitionConditionally<CancellationEvent> {
    direction = {
        if (sourceState is CancellableState && sourceState.cancellable) {
            targetState(CancellingState)
        } else {
            noTransition()
        }
    }
}
```
But the `sourceState` is `protected` now and I cannot use it. 
Do you think it might be valuable to open the variable for cases like mine?

**Comment by nsk90** [comment]
Hi, thank you!
At first glance, your attempt is valid, I have to check why the field is protected and not available, and findout maybe other sintax is available. I'll do it on a next week. 

Are you ready to open a PR if we will finish with making it public?

**Comment by nsk90** [comment]
A am not am laptop now, and can't surely check it, but as I see the `sourceState` here is a reference to the parent state of a transition, but you are assuming as it is a current machine state. As `KStateMachine` supports hierarchy and parallel states, there might be many current states, they are retrieved by `activeStates()` function. Try using `activeStates()` instead of `sourceState`.

**Comment by Zeliret** [comment]
I see. Okay, let me try `activeStates()` on Monday, thank you!

**Comment by Zeliret** [comment]
It works and I was able to achieve the logic described in the post. Thank you for the advice!
