### ISSUE TITLE
how to transition dataState by normal event

### ISSUE THREAD

**Issue by pujunhui** [KStateMachine/kstatemachine#108]
we want to transition to DataState by normal Event, how i can do？

``` kotlin
  private val machine: StateMachine = createStateMachineBlocking(
      scope = scope,
      name = "Test"
  ) {

      val idle = initialState("init")
      val working = dataState<String>("working")

      idle {
            transitionOn<StartEvent> {
                onTriggered {
                    val token = getToken()
//                    targetState = working //error
                    //we want to jump to working state, and with token
                }
            }
      }
  }

  private suspend fun getToken(): String {
      delay(1000L)
      return "123"
  }

  suspend fun start() {
      machine.processEvent(StartEvent)
  }

  object StartEvent : Event
```

**Comment by nsk90** [comment]
Hi!
You can target `DataState` with Non-DataEvent only by `transitionConditionally` function. This is the most powerful and flexible function to create transitions, so it allows to create such "not type safe" transitions (as foul of last resort).

In this case your `DataState` will be activated with previous data (from last activation), if there were no previous data it will use `defaultData` from its constructor. If the `defaultData` was not set also, the runtime exception will be thrown. 

There is no way to send data to `DataState` other then `DataEvent`. If you cannot use `DataEvent` (and need to send data to a state), just use simple `DefaultState` subclass with new property (to store your data). Alternatively you can use builtin non-typesafe `payload` property.

`DataEvent` and `DataState`  are APIs to pass data between each other in type-safe way with compile-time guaranties. So they should be used together to operate correctly. If there usage scenario is to strict for you, you can just not use them.

**Comment by nsk90** [comment]
As I see you code structure you may also use `transition argument` API to pass token reference.

**Comment by pujunhui** [comment]
Thanks for your reply. I have another question. If I need to run a time-consuming task in a state, how can I do it without blocking the state machine?

**Comment by pujunhui** [comment]
If I perform time-consuming operations in onEntry, I will not receive any events in this state.

**Comment by nsk90** [comment]
You can launch expensive calculation in a coroutine on machines coroutineScope using standard `kotlinx.coroutines.launch` function.

I suppose if you send an event while the machine is blocked by calculation, the event will be processed after the calculation ends. If id does not fit your usescase, and you need to have a machine that responds to events while processing the calculation, calculation should be done I parallel. so the `launch` is the only way.
