### ISSUE TITLE
`addInitialState` and `addState` compiler errors since version `0.32.0`

### ISSUE THREAD

**Issue by drindt** [KStateMachine/kstatemachine#110]
## addInitialState and addState compiler errors since version 0.32.0

Since updating to version 0.32.0, I'm encountering compiler errors when using `addInitialState` and `addState`.

**addInitialState:**

The `addInitialState` function now produces the following error: `Suspension functions can only be called within coroutine body.` This appears to be a breaking change that was not documented.

**addState:**

The `addState` function now produces the following error: `Too many arguments for 'fun <S : IState> addState(state: S): S'`. I'm unsure what has changed to cause this error, as I couldn't find any relevant information in the version diff.

Has anyone else encountered these issues or have any advice on how to resolve them?

**Additional Information:**

* **KStateMachine version:** 0.32.0
* **Kotlin version:** 2.0.21

**Comment by nsk90** [comment]
Hi, could you provide, sample of your code structure? I am interested in a place where `addInitialState` and  `addState ` are called from.
Is it possible to make that place `suspendable`?

In last release I have changed signature of several dsl methods including `addInitialState`, `addState ` to `suspendable`.
Sorry I assumed that those methods are called inside suspendable code blocks, or that is will be easy to change client code to make it suspendable.

To fix `Too many arguments ` error you need an import for correct `addState` extension method. (but I assume you will have the same error as for `addInitialState ` after applying correct import).

**Comment by drindt** [comment]
Please have a look here:
```kotlin
createStateMachine(
    scope = scope,
) {
    state(
    ) {
        addInitialState(Close) {
            onEntry {
                  // ...
            }
            transition<Opened> {
                guard = { /* ... */ }
                targetState = Open
            }
        }

        addState(Open) {
            onEntry {
                // ...
            }
            transition<Closed> {
                guard = { /* ... */ }
                targetState = Close
            }
        }
    }
}

Helps this information? Thank you for your efforts.

**Comment by nsk90** [comment]
![image](https://github.com/user-attachments/assets/c9d630f4-0870-4b40-8577-f8144754c172)

I cant reproduce the issue with this sample, it compiles. Are you sure that it should reproduce the problem?

**Comment by drindt** [comment]
Can you show me your `import`s please?

**Comment by nsk90** [comment]
```kotlin
package ru.nsk.kstatemachine.state

import io.kotest.core.spec.style.StringSpec
import ru.nsk.kstatemachine.event.Event
import ru.nsk.kstatemachine.statemachine.createStateMachine

private object Close : DefaultState()
private object Open : DefaultState()

private object Closed : Event
private object Opened : Event

class StateTest : StringSpec({

        "issue" {
            createStateMachine(
                scope = this,
            ) {
                state(
                ) {
                    addInitialState(Close) {
                        onEntry {
                            // ...
                        }
                        transition<Opened> {
                            guard = { /* ... */true }
                            targetState = Open
                        }
                    }

                    addState(Open) {
                        onEntry {
                            // ...
                        }
                        transition<Closed> {
                            guard = { /* ... */true }
                            targetState = Close
                        }
                    }
                }
            }
        }

})
```

**Comment by nsk90** [comment]
```kotlin
package test.nsk.issue

import io.kotest.core.spec.style.StringSpec
import ru.nsk.kstatemachine.event.Event
import ru.nsk.kstatemachine.state.DefaultState
import ru.nsk.kstatemachine.state.addInitialState // I suppose you need this one
import ru.nsk.kstatemachine.state.onEntry
import ru.nsk.kstatemachine.state.state
import ru.nsk.kstatemachine.state.transition
import ru.nsk.kstatemachine.state.addState // and this
import ru.nsk.kstatemachine.statemachine.createStateMachine

private object Close : DefaultState()
private object Open : DefaultState()

private object Closed : Event
private object Opened : Event

class StateTest : StringSpec({

        "issue" {
            createStateMachine(
                scope = this,
            ) {
                state(
                ) {
                    addInitialState(Close) {
                        onEntry {
                            // ...
                        }
                        transition<Opened> {
                            guard = { /* ... */true }
                            targetState = Open
                        }
                    }

                    addState(Open) {
                        onEntry {
                            // ...
                        }
                        transition<Closed> {
                            guard = { /* ... */true }
                            targetState = Close
                        }
                    }
                }
            }
        }

})
```

**Comment by drindt** [comment]
Mikhail, thank you very much again for digging into this. But i am actually using exactly those imports.

**Comment by nsk90** [comment]
Interesting, what is your Kotlin version?

**Comment by nsk90** [comment]
I have updated to Kotlin 2.0.21 and still cannot reproduce it(

**Comment by drindt** [comment]
Really strange thing, i have cleared up everything from build and gradle folders. It is maybe related to the K2 compiler?
This btw works:
![image](https://github.com/user-attachments/assets/a1e6c817-b396-4588-875e-8c9017ba2dfe)

**Comment by nsk90** [comment]
I agree, it looks like k2 mode problem, but I am using it also, and do not face the issue)

**Comment by drindt** [comment]
Ok, thank you for your kind assistance.

**Comment by nsk90** [comment]
IntelliJ IDEA 2024.3 is out, with Stable Kotlin K2 mode.

Please, let me know if it fixes this problem for you, when you'll be ready to update it.

**Comment by drindt** [comment]
On my end it builds after adding `import ru.nsk.kstatemachine.state.addState`. But the IDE shows still strange errors. Thank you for your kind assistance.
