### ISSUE TITLE
Sources are not packaged correctly

### ISSUE THREAD

**Issue by reactormonk** [KStateMachine/kstatemachine#86]
According to https://issuetracker.google.com/issues/320626494#comment4 there's a bug in the gradle build.

**Comment by nsk90** [comment]
I have checked with https://github.com/nsk90/android-kstatemachine-sample sample that IDE successfully shows source code documentation while working with the library artifact.
Please provide detailed info what is the problem and steps to reproduce it.

**Comment by nsk90** [comment]
closing as stale
