### ISSUE TITLE
Event queue is not empty, internal error

### ISSUE THREAD

**Issue by oyanyev** [KStateMachine/kstatemachine#96]
Sometimes I get an `error: java.lang.IllegalStateException: Event queue is not empty, internal error` which invalidates state machine. I tried to research, but it did not become clearer to me

Questions:
1. What is the exact reason of that? 
2. How to avoid it?
3. Is that really necessary to throw?

**Comment by oyanyev** [comment]
coroutines version. 

Thanx. I got the idea. Will dig further.

**Comment by oyanyev** [comment]
Issue hopefully is gone

**Comment by nsk90** [comment]
was it related to multithreading usage?

**Comment by oyanyev** [comment]
Since I used single thread dispatcher, i have not seen it. If It appear again, I definitely notify you
